package com.seleniumToolkit.selenium.pageObject

import com.seleniumToolkit.selenium.pageObject.template.AbstractSeleniumToolkitPageObject

//PO generated by SeleniumToolkit-Extension
class About : AbstractSeleniumToolkitPageObject() {
    val URL = "/about/"
}