package com.seleniumToolkit.selenium.pageObject

import com.seleniumToolkit.selenium.pageObject.template.AbstractSeleniumToolkitPageObject
import org.openqa.selenium.WebElement
import org.openqa.selenium.support.FindBy

//PO generated by SeleniumToolkit-Extension
class ChromeExtension : AbstractSeleniumToolkitPageObject() {
    val URL = "/chromeextension/"

    //Field declarations
    @FindBy(xpath = "//*[@id='fusion-tab-descriptionvideo']")
    var tabDescriptionVideo: WebElement? = null

    @FindBy(xpath = "//*[@id='fusion-tab-tutorialvideo']")
    var tabTutorialvideo: WebElement? = null

    @FindBy(xpath = "//a[.//*[contains(text(),'GET STARTED')]]")
    var getStartedButton: WebElement? = null

    //HelperMethods
    fun clickTabDescriptionVideo() {
        click(tabDescriptionVideo!!)
    }

    fun clickTabTutorialvideo() {
        click(tabTutorialvideo!!)
    }

    fun clickGetStartedButton(): GetStarted {
        click(getStartedButton!!)
        return GetStarted()
    }
}