package com.seleniumToolkit.selenium.pageObject

import com.seleniumToolkit.selenium.pageObject.template.AbstractSeleniumToolkitPageObject
import org.openqa.selenium.WebElement
import org.openqa.selenium.support.FindBy

//PO generated by SeleniumToolkit-Extension
class Home : AbstractSeleniumToolkitPageObject() {
    val URL = "/"

    //Field declarations
    @FindBy(xpath = "//*[contains(@class,'button-1')]")
    var solutionButton: WebElement? = null

    @FindBy(xpath = "//a[.//*[contains(text(),'GET STARTED')]]")
    var getStartedButton: WebElement? = null

    //HelperMethods
    fun clickSolutionButton(): Solution {
        click(solutionButton!!)
        return Solution()
    }

    fun clickGetStartedButton(): GetStarted {
        click(getStartedButton!!)
        return GetStarted()
    }
}