package com.seleniumToolkit.selenium.pageObject

import com.seleniumToolkit.selenium.pageObject.template.AbstractSeleniumToolkitPageObject
import org.openqa.selenium.WebElement
import org.openqa.selenium.support.FindBy

//PO generated by SeleniumToolkit-Extension
class SeleniumHelp : AbstractSeleniumToolkitPageObject() {
    val URL = "/selenium-help/"

    //Field declarations
    @FindBy(xpath = "//*[@aria-controls='tab-BrokenImages']")
    var tabBrokenImages: WebElement? = null

    @FindBy(xpath = "//*[@aria-controls='tab-ContextMenu']")
    var tabContextMenu: WebElement? = null

    @FindBy(xpath = "//*[@aria-controls='tab-DragDrop']")
    var tabDragDrop: WebElement? = null

    @FindBy(xpath = "//*[@aria-controls='tab-FileDownload']")
    var tabFileDownload: WebElement? = null

    @FindBy(xpath = "//*[@aria-controls='tab-Iframe']")
    var tabIframe: WebElement? = null

    @FindBy(xpath = "//*[@aria-controls='tab-JSAlert']")
    var tabJSAlert: WebElement? = null

    @FindBy(xpath = "//*[@aria-controls='tab-JsLogin_BasicAuthPopUp']")
    var tabJsLogin_BasicAuthPopUp: WebElement? = null

    @FindBy(xpath = "//*[@aria-controls='tab-NewWindow']")
    var tabNewWindow: WebElement? = null

    @FindBy(xpath = "//*[@aria-controls='tab-Hover']")
    var tabHover: WebElement? = null

    @FindBy(xpath = "//*[@aria-controls='tab-PageObjects']")
    var tabPageObjects: WebElement? = null

    @FindBy(xpath = "//*[@aria-controls='tab-Selectors']")
    var tabSelectors: WebElement? = null

    @FindBy(xpath = "//*[@aria-controls='tab-ShadowDOM']")
    var tabShadowDOM: WebElement? = null

    @FindBy(xpath = "//*[@aria-controls='tab-Table']")
    var tabTable: WebElement? = null

    @FindBy(xpath = "//*[@aria-controls='tab-Waits']")
    var tabWaits: WebElement? = null

    //HelperMethods
    fun clickTabBrokenImages() {
        click(tabBrokenImages!!)
    }

    fun clickTabContextMenu() {
        click(tabContextMenu!!)
    }

    fun clickTabDragDrop() {
        click(tabDragDrop!!)
    }

    fun clickTabFileDownload() {
        click(tabFileDownload!!)
    }

    fun clickTabIframe() {
        click(tabIframe!!)
    }

    fun clickTabJSAlert() {
        click(tabJSAlert!!)
    }

    fun clickTabJsLogin_BasicAuthPopUp() {
        click(tabJsLogin_BasicAuthPopUp!!)
    }

    fun clickTabNewWindow() {
        click(tabNewWindow!!)
    }

    fun clickTabHover() {
        click(tabHover!!)
    }

    fun clickTabPageObjects() {
        click(tabPageObjects!!)
    }

    fun clickTabSelectors() {
        click(tabSelectors!!)
    }

    fun clickTabShadowDOM() {
        click(tabShadowDOM!!)
    }

    fun clickTabTable() {
        click(tabTable!!)
    }

    fun clickTabWaits() {
        click(tabWaits!!)
    }
}