package com.seleniumToolkit.selenium.pageObject

import com.seleniumToolkit.selenium.pageObject.template.AbstractSeleniumToolkitPageObject

//PO generated by SeleniumToolkit-Extension
class Solution : AbstractSeleniumToolkitPageObject() {
    val URL = "/solutions/"
}